# services:
#   api:
#     build: .
#     ports:
#       - "3000:3000"
#     env_file:
#       - .env
#     environment:
#       DATABASE_URL: mongodb://mongo:27017/task-manager
#     depends_on:
#       - mongo

#   mongo:
#     image: mongo:8
#     volumes:
#       - mongo-data:/data/db

# volumes:
#   mongo-data:

# //================================

# # we use redius now so use this instead of above
# services:
#   api:
#     build: .

#     ports:
#       - "3000:3000"

#     env_file:
#       - .env

#     environment:
#       DATABASE_URL: mongodb://mongo:27017/task-manager
#       REDIS_HOST: redis
#       REDIS_PORT: 6379

#     depends_on:
#       - mongo
#       - redis

#   mongo:
#     image: mongo:8

#     volumes:
#       - mongo-data:/data/db

#   redis:
#     image: redis:8-alpine

#     ports:
#       - "6379:6379"

# volumes:
#   mongo-data:

# //================================
# now add worker

services:
  api:
    build: .

    ports:
      - "3000:3000"

    env_file:
      - .env

    environment:
      DATABASE_URL: mongodb://mongo:27017/task-manager
      REDIS_HOST: redis
      REDIS_PORT: 6379

    depends_on:
      - mongo
      - redis

  worker:
    build: .

    command: npm run worker:tasks

    env_file:
      - .env

    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379

    depends_on:
      - redis

  mongo:
    image: mongo:8

    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:8-alpine

    ports:
      - "6379:6379"

volumes:
  mongo-data: