name: Task Manager CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  backend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: task-manager-api

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v7
        with:
          node-version: "20.x"
          cache: npm
          cache-dependency-path: task-manager-api/package-lock.json

      - name: Install backend dependencies
        run: npm ci

      - name: Run backend tests
        run: npm test


  frontend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: task-manager-frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v7
        with:
          node-version: "20.x"
          cache: npm
          cache-dependency-path: task-manager-frontend/package-lock.json

      - name: Install frontend dependencies
        run: npm ci

      - name: Run frontend lint
        run: npm run lint

      - name: Build frontend
        run: npm run build